### ISSUE TITLE
With async atomic select is ok but get failed

### ISSUE THREAD

**Issue by jiamo** [05bit/peewee-async#164]
```
    async with misc.aio_dbm.atomic() as t:
        item = await misc.aio_dbm.execute(AdUnit.select(AdUnit).where(AdUnit.id == 1))  # Is ok
        item = await misc.aio_dbm.execute(AdUnit.get(AdUnit.id == 1)) #  is wrong
        breakpoint()
```
the error is such like

```
Traceback (most recent call last):
  File "/Users/jiamo/data/test/.venv/lib/python3.10/site-packages/peewee.py", line 3158, in execute_sql
    cursor = self.cursor(commit)
  File "/Users/jiamo/data/test/.venv/lib/python3.10/site-packages/peewee.py", line 3144, in cursor
    raise InterfaceError('Error, database connection not opened.')
peewee.InterfaceError: Error, database connection not opened.
```
So why  `get` is so different with the `select`.

**Comment by kalombos** [comment]
Because **get** method is a shortcut to run query using synchronous peewee. Use
```python
await misc.aio_dbm.get(AdUnit, id = 1)
```
instead
