### ISSUE TITLE
get_or_none doesn't work as expected

### ISSUE THREAD

**Issue by fruitoiz** [05bit/peewee-async#206]
**get_or_none не работает с User.select()
get_or_none doesn't work with User.select()**

code: `info = await objects.get_or_none(User.select().where(User.user_id==1))`

**expected to receive / ожидал получить: `None`**

**Received / Получил:** 

```
Traceback (most recent call last):
  File "/home/USRRD/.local/lib/python3.12/site-packages/peewee_async.py", line 176, in get
    return list(result)[0]
           ~~~~~~~~~~~~^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USRRD/.local/lib/python3.12/site-packages/peewee_async.py", line 207, in get_or_none
    return (await self.get(model_, *args, **kwargs))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USRRD/.local/lib/python3.12/site-packages/peewee_async.py", line 178, in get
    raise model.DoesNotExist
database.models.UserDoesNotExist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/USRRD/projects/bots/__main__.py", line 45, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/USRRD/projects/bots/__main__.py", line 39, in main
    info = await objects.get_or_none(User.select().where(User.user_id==10131433030))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USRRD/.local/lib/python3.12/site-packages/peewee_async.py", line 208, in get_or_none
    except model_.DoesNotExist:
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'ModelSelect' object has no attribute 'DoesNotExist'

```

**An example of a solution to an error  /  Пример решения ошибки** 
```
    async def get_or_none(self, model_, *args, **kwargs):
        """Try to get an object and return None if it doesn't exist."""
        try:
            return (await self.get(model_, *args, **kwargs))
        except peewee.DoesNotExist:
            pass

```

**Comment by kalombos** [comment]
Try to use  ```info = await objects.get_or_none(User, user_id==1)```,  or better yet, use [new api ](https://peewee-async-lib.readthedocs.io/en/latest/peewee_async/api.html#peewee_async.AioModel.aio_get_or_none) ``````info = await User.aio_get_or_none(user_id==1)```

**Comment by kalombos** [comment]
Just a bit convenient and follow the sync peewee style. Also Manager class seems redundant and will be removed next versions

**Comment by kalombos** [comment]
No. You can see all methods of the api in the documentation.
