### ISSUE TITLE
AttributeError: 'playhouse._speedups._ModelQueryResultWrapper' object has no attribute 'initialize'

### ISSUE THREAD

**Issue by NewVadim** [05bit/peewee-async#34]
I got an error after I installed peewee=2.8.2

```
Traceback (most recent call last):
  File "/home/user/project/env/lib/python3.5/site-packages/aiohttp/server.py", line 266, in start
    yield from self.handle_request(message, payload)
  File "/home/user/project/env/lib/python3.5/site-packages/aiohttp/web.py", line 90, in handle_request
    resp = yield from handler(request)
  File "/home/user/project/env/lib/python3.5/site-packages/aiohttp_session/__init__.py", line 129, in middleware
    response = yield from handler(request)
  File "/home/user/project/src/account/middleware.py", line 19, in middleware
    request.user = await User.objects.get(User, id=user_id)
  File "/home/user/project/env/lib/python3.5/site-packages/peewee_async.py", line 151, in get
    result = yield from self.execute(query.limit(1))
  File "/home/user/project/env/lib/python3.5/site-packages/peewee_async.py", line 251, in execute
    return (yield from execute(query))
  File "/home/user/project/env/lib/python3.5/site-packages/peewee_async.py", line 418, in execute
    return (yield from coroutine(query))
  File "/home/user/project/env/lib/python3.5/site-packages/peewee_async.py", line 565, in select
    yield from result.fetchone()
  File "/home/user/project/env/lib/python3.5/site-packages/peewee_async.py", line 789, in fetchone
    self._result_wrapper.initialize(self._cursor.description)
AttributeError: 'playhouse._speedups._ModelQueryResultWrapper' object has no attribute 'initialize'
```

**Comment by rudyryk** [comment]
@NewVadim Thanks for the report, I'll take a look!

**Comment by rudyryk** [comment]
@NewVadim I can reproduce this with peewee==2.8.2, but can't with current version from master branch. Actually, `_ModelQueryResultWrapper` do have `initialize()` according to the source https://github.com/coleifer/peewee/blob/8cfec65776b3655a7b42edbe45530eed152d80a7/playhouse/_speedups.pyx#L142

Not sure how to treat that :)

**Comment by rudyryk** [comment]
Ok, as far as I see, we can't just use wrappers from `_speedups` and, actually, we didn't use them before.
