### ISSUE TITLE
Help! KeyError: 'A@>' when using ArrayField

### ISSUE THREAD

**Issue by qwexvf** [05bit/peewee-async#58]
Query
```
        lobbies = await db.execute(Lobby.select().where(
            (Lobby.members.contains(user['steam_id'])) & (Lobby.id != lobby_id))
        )
```
Model
```
class Lobby(BaseModel):
    members = ArrayField(CharField, default=list)
```
Error
```
2017-03-14 00:10:22,513: ERROR: Traceback (most recent call last):                                                                                 W5pYy9saWIvcHl0aG9uMy42L3NpdGUtcGFja2FnZ  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/sanic/app.py", line 391, in handle_request                                  L3B1Zy9hcHAvdXRpbHMucHkiLCBsaW5lIDk2LCBp    response = await response                                                                                                                      2aWV3cy9sb2JieS5weSIsIGxpbmUgNTUsIGluIGF  File "/home/qwexvf/Documents/work/pug/app/utils.py", line 96, in decorated_function                                                              dleHZmLy5weWVudi92ZXJzaW9ucy9zYW5pYy9saW    response = await f(req, *args, **kwargs)                                                                                                       CIvaG9tZS9xd2V4dmYvLnB5ZW52L3ZlcnNpb25zL  File "/home/qwexvf/Documents/work/pug/app/views/lobby.py", line 55, in api_lobby_info                                                            eSkpCiAgRmlsZSAiL2hvbWUvcXdleHZmLy5weWVu    lobbies = await db.execute(Lobby.select().where((Lobby.members.contains())))                                                                   lY3V0ZV9xdWVyeV9hc3luYyhxdWVyeSkKICBGaWx  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee_async.py", line 269, in execute                                      J5X2FzeW5jCiAgICByZXR1cm4gKHlpZWxkIGZyb2    return (yield from execute(query))                                                                                                             XMvcGVld2VlLnB5IiwgbGluZSAzMTc0LCBpbiBzc  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee_async.py", line 433, in execute                                      dGUtcGFja2FnZXMvcGVld2VlLnB5IiwgbGluZSAx    return (yield from coroutine(query))                                                                                                           hbmljL2xpYi9weXRob24zLjYvc2l0ZS1wYWNrYWd  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee_async.py", line 574, in select                                       9xd2V4dmYvLnB5ZW52L3ZlcnNpb25zL3NhbmljL2    cursor = yield from _execute_query_async(query)                                                                                                WxpYXNfbWFwLCBjb252KQogIEZpbGUgIi9ob21lL  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee_async.py", line 1518, in _execute_query_async                        bGYuX3BhcnNlX21hcFtub2RlX3R5cGVdKG5vZGUs    return (yield from _run_sql(query.database, *query.sql()))                                                                                     sIGluIF9wYXJzZV9jbGF1c2UKICAgIG5vZGUubm9  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 3174, in sql                                               5weSIsIGxpbmUgMTg2MywgaW4gcGFyc2Vfbm9kZV    return self.compiler().generate_select(self)                                                                                                   2FuaWMvbGliL3B5dGhvbjMuNi9zaXRlLXBhY2thZ  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1999, in generate_select                                   L2hvbWUvcXdleHZmLy5weWVudi92ZXJzaW9ucy9z    return self.build_query(clauses, alias_map)                                                                                                    obm9kZSwgYWxpYXNfbWFwLCBjb252KQogIEZpbGU  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1885, in build_query                                       AgIHNxbCA9IHRlbXBsYXRlICUgKGxocywgc2VsZi    return self.parse_node(Clause(*clauses), alias_map)                                                                                            DE2OTQsIGluIGdldF9vcAogICAgcmV0dXJuIHNlb  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1838, in parse_node                                        │                                       
    sql, params, unknown = self._parse(node, alias_map, conv)                                                                                      │                                       
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1804, in _parse                                            │                                       
    sql, params = self._parse_map[node_type](node, alias_map, conv)                                                                                │                                       
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1735, in _parse_clause                                     │                                       
    node.nodes, alias_map, conv, node.glue)                                                                                                        │                                       
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1863, in parse_node_list                                   │                                       
    node_sql, node_params = self.parse_node(node, alias_map, conv)                                                                                 │                                       
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1838, in parse_node                                        │                                       
    sql, params, unknown = self._parse(node, alias_map, conv)                                                                                      │                                       
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1804, in _parse                                            │                                       
    sql, params = self._parse_map[node_type](node, alias_map, conv)                                                                                │                                       
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1710, in _parse_expression                                 │                                       
    sql = template % (lhs, self.get_op(node.op), rhs)                                                                                              │                                       
  File "/home/qwexvf/.pyenv/versions/sanic/lib/python3.6/site-packages/peewee.py", line 1694, in get_op                                            │                                       
    return self._op_map[q]                                                                                                                         │                                       
KeyError: 'A@>'     
```

i think the problem is with ```(Lobby.members.contains(user['steam_id'])```
if so how can i deal with arrayfield?

**Comment by rudyryk** [comment]
@qwexvf Have you tried to run query without peewee-async? I mean, just with peewee.

**Comment by qwexvf** [comment]
@rudyryk Hi, i just did a quick test but yes it works normal.
the test i did:
```
Python 3.6.0 (default, Feb 16 2017, 22:02:56)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from old_db import db, Lobby
>>> for lob in Lobby.select().where((Lobby.members.contains('76561198119197701')) & (Lobby.id != 1)):
...     print(lob.members)
...
>>> for lob in Lobby.select().where((Lobby.members.contains('76561198119197701'))):
...     print(lob.members)
...
['76561198119197701']
>>>
```
first query shows nothing because i put the (Lobby.id != 1) which ignore that specific lobby

Thanks !!!

**Comment by qwexvf** [comment]
Another quick question, i have a class method which is something like 
```
class Lobby(BaseModel):
    owner = ForeignKeyField(User)

    def can_join(self, steam_id):
        if self.owner == steam_id:
            return True
        elif len(self.members) <= 5:
            return True
        else:
            return False
```
then when i do ``` lobby = await db.get(Lobby, id=lobby_id) ```
and use the class method
``` lobby.can_join(steamid) ```
it says 
```
AssertionError: Error, sync query is not allowed! Call the `.set_allow_sync()` or use the `.allow_sync()` context manager.
```
i dont get it can you help me ?

**Comment by qwexvf** [comment]
Okay, i found out  that there's  ```peewee_asyncext ``` then. i changed my database to something like 
```database = peewee_asyncext.PostgresqlExtDatabase() ``` and this fixed the ``` KeyError: 'A@>'```

Buttt,  i got something new instead lol. 

``` peewee.ProgrammingError: can't adapt type 'User' ```

anyone know what this is ? maybe ``` ForeignKeyField ``` is not ok?

**Comment by joaodlf** [comment]
I have the exact same problem. Latest Peewee version, not using peewee_asyncext.

Model:
```
from playhouse.postgres_ext import *
...
col_test = ArrayField(CharField)
...
```

```
 where = [... , Extras.col_test.contains("test")]

extras = Extras \
.select() \
.where(*where)
```

Throw a `KeyError: 'A@>'`, much like the original report.
