### ISSUE TITLE
'AsyncQueryWrapper' object does not support indexing (since 0.5.8)

### ISSUE THREAD

**Issue by tomvlk** [05bit/peewee-async#77]
Since upgrading to 0.5.8 (and as well 0.5.9) I get the following error:

```
ERROR    [test2][pyplanet.core.instance] 'AsyncQueryWrapper' object does not support indexing
Traceback (most recent call last):
  File "/home/tom/IdeaProjects/maniaplanet/pyplanet-core/pyplanet/core/instance.py", line 121, in start
    self.loop.run_until_complete(self._start())
  File "/home/tom/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/home/tom/IdeaProjects/maniaplanet/pyplanet-core/pyplanet/core/instance.py", line 182, in _start
    await self.apps.start()
  File "/home/tom/IdeaProjects/maniaplanet/pyplanet-core/pyplanet/apps/apps.py", line 187, in start
    await app.on_start()
  File "/home/tom/IdeaProjects/maniaplanet/pyplanet-core/pyplanet/apps/contrib/local_records/__init__.py", line 61, in on_start
    await self.load_map_locals()
  File "/home/tom/IdeaProjects/maniaplanet/pyplanet-core/pyplanet/apps/contrib/local_records/__init__.py", line 65, in load_map_locals
    map.local = await self.get_map_record(map)
  File "/home/tom/IdeaProjects/maniaplanet/pyplanet-core/pyplanet/apps/contrib/local_records/__init__.py", line 77, in get_map_record
    'first_record': record_list[0] if len(record_list) > 0 else None
TypeError: 'AsyncQueryWrapper' object does not support indexing
```

Project can be found here: https://github.com/PyPlanet/PyPlanet

Is this intentional or a bug?

Thanks :-)

**Comment by rudyryk** [comment]
@tomvlk Thank you for reporting! This is a bug due to missing `__getitem__` in these versions.

**Comment by tomvlk** [comment]
What a speed! Thanks @rudyryk
